name: build and push

on:
  push:
    - env-test
    - env-qa


permissions:
  contents: read
  packages: write

jobs:
  buildn-and-deploy:
    name: build & deploy
    runs-on:
      - self-hosted

    enviroment: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: build and setting docker enviromnet on server

    run:
      docker-compose -f ./docker-compose/docker-compose.yml -p mapbook_pk up --build -d

